---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required  packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: network_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=600
  with_items: network_pkgs
  environment: env
  when: ansible_os_family == 'Debian'


- name: Make sure the include line is there in interfaces file
  lineinfile: >
     regexp="^source\ \/etc\/network\/interfaces.d\/\*"
     line="source /etc/network/interfaces.d/*"
     dest=/etc/network/interfaces
     state=present
     insertafter=EOF
  when: ansible_os_family == "Debian"

- name: Create the directory for interface cfg files
  file: path=/etc/network/interfaces.d  state=directory
  when: ansible_os_family == "Debian"

- name: Create the network configuration file for ethernet devices
  template: src=ethernet_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: network_ether_interfaces
  when: network_ether_interfaces is defined
  register: ether_result

- name: Write configuration files for rhel route configuration
  template: src=route_{{ ansible_os_family }}.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: network_ether_interfaces
  when: network_ether_interfaces is defined and item.route is defined and ansible_os_family == 'RedHat'

- shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: ether_result.results
  when: ether_result is defined and item.changed

- name: Create the network configuration file for bridge devices
  template: src=bridge_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: network_bridge_interfaces
  when: network_bridge_interfaces is defined
  register: bridge_result

- name: Write configuration files for rhel route configuration
  template: src=route_{{ ansible_os_family }}.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: network_bridge_interfaces
  when: network_bridge_interfaces is defined and item.route is defined and ansible_os_family == 'RedHat'

- shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: bridge_result.results
  when: bridge_result is defined and item.changed

# - name: Create /etc/iproute2/rt_tables entry for each source route bridge devices
#   lineinfile: >
#      regexp="^{{item.1}}\W+{{item.1}}"
#      line="{{item.1}}\t{{item.1}}}"
#      dest=/etc/iproute2/rt_tables
#      state=present
#      insertafter=EOF
#   with_subelements:
#     - network_bridge_interfaces|default([])
#     - source_rt
#     - skip_missing: yes  ### NOTES when this is working we can do it this way
#   when: network_bridge_interfaces is defined and item.0.source_rt is defined

- name: Create /etc/iproute2/rt_tables entry for each source route bridge devices
  lineinfile: >
     regexp="^{{item.id}}\W+{{item.name}}"
     line="{{item.id}}\t{{item.name}}"
     dest=/etc/iproute2/rt_tables
     state=present
     insertafter=EOF
  with_items: source_routing_tables
  when: source_routing_tables is defined
  tags: source_routing

- name: Create the network configuration file for port on the bridge devices
  template: src=bridge_port_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.1 }}
  with_subelements:
   - network_bridge_interfaces
   - ports
  when: network_bridge_interfaces is defined
  register: bridge_port_result

- shell: ifdown {{ item.item.1 }}; ifup {{ item.item.1 }}
  with_items: bridge_port_result.results
  when: bridge_port_result is defined and item.changed

- name: Create the network configuration file for bond devices
  template: src=bond_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: network_bond_interfaces
  when: network_bond_interfaces is defined
  register: bond_result

- name: Make sure the bonding module is loaded
  modprobe: name=bonding state=present
  when: bond_result|changed

- name: Write configuration files for route configuration
  template: src=route_{{ ansible_os_family }}.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: network_bond_interfaces
  when: network_bond_interfaces is defined and item.route is defined and ansible_os_family == 'RedHat'

- shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: bond_result.results
  when: bond_result is defined and item.changed

- name: Create the network configuration file for slave in the bond devices
  template: src=bond_slave_{{ ansible_os_family }}.j2 dest={{ net_path }}/ifcfg-{{ item.1 }}
  with_subelements:
   - network_bond_interfaces
   - bond_slaves
  when: network_bond_interfaces is defined
  register: bond_port_result

- shell: ifdown {{ item.item.1 }}; ifup {{ item.item.1 }}
  with_items: bond_port_result.results
  when: bond_port_result is defined and item.changed

- shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: bond_result.results
  when: bond_result is defined and item.changed and ansible_os_family == 'RedHat'
